apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zphexk373-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zphexk373-go 
  name: zphexk373-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zphexk373-go 
